# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "floppy" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/fcd46cce-fca4-430c-8694-68bfe9f9e892";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/038e9f7f-12a7-4e8d-81ee-984cebb5977b"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
